trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_HOST_URL: 'https://sonarcloud.io'
  SONAR_PROJECT_KEY: 'tatsianabaldouskaya_Web_api_app'
  SONAR_ORG_KEY: 'tatsianabaldouskaya-1'
  COVERAGE_FOLDER: '$(System.DefaultWorkingDirectory)/TestResults'
  COVERAGE_FILE: '$(COVERAGE_FOLDER)/coverage.opencover.xml'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: 'Build the Project'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'sonarToken1'
      organization: 'tatsianabaldouskaya-1'
      scannerMode: 'dotnet'
      projectKey: 'tatsianabaldouskaya_Web_api_app'

  - task: SonarCloudAnalyze@3
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~Tests.UnitTests'