trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_HOST_URL: 'https://sonarcloud.io'
  SONAR_PROJECT_KEY: 'tatsianabaldouskaya_Web_api_app'
  SONAR_ORG_KEY: 'tatsianabaldouskaya-1'
  COVERAGE_FOLDER: '$(System.DefaultWorkingDirectory)'
  COVERAGE_FILE: '$(COVERAGE_FOLDER)/coverage.cobertura.xml'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self
    fetchDepth: 0 

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'sonarToken1'
      organization: 'tatsianabaldouskaya-1'
      scannerMode: 'dotnet'
      projectKey: 'tatsianabaldouskaya_Web_api_app'
      extraProperties: |
        sonar.cs.xunit.reportsPaths=$(Build.SourcesDirectory)/test-results.trx
        sonar.coverage.cobertura.reportPaths=$(Build.SourcesDirectory)/CoverageReport/Cobertura.xml

  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build the Project'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~Tests.UnitTests --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test-results.trx"'

  - script: dotnet tool install -g dotnet-reportgenerator-globaltool
    displayName: 'Install ReportGenerator'

  - script: |
      reportgenerator \
        -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml \
        -targetdir:$(Build.SourcesDirectory)/CoverageReport \
        -reporttypes:Cobertura
    displayName: 'Generate Cobertura Coverage Report'

  - task: SonarCloudAnalyze@3
  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'