pr: none
trigger: 
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_HOST_URL: 'https://sonarcloud.io'
  SONAR_PROJECT_KEY: 'tatsianabaldouskaya_Web_api_app'
  SONAR_ORG_KEY: 'tatsianabaldouskaya-1'
  COVERAGE_FOLDER: '$(Agent.TempDirectory)'
  COVERAGE_FILE: '$(COVERAGE_FOLDER)/coverage.cobertura.xml'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self
    fetchDepth: 0 

  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'sonarToken1'
      organization: 'tatsianabaldouskaya-1'
      scannerMode: 'dotnet'
      projectKey: $(SONAR_PROJECT_KEY)
      extraProperties: |
        sonar.cs.xunit.reportsPaths=$(Build.SourcesDirectory)/test-results.trx
        sonar.coverage.cobertura.reportPaths=$(COVERAGE_FILE)
        sonar.scanner.scanAll=false
        sonar.branch.name=main

  - task: DotNetCoreCLI@2
    displayName: 'Build the Project'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~Tests.UnitTests --collect "Code Coverage" --logger:"trx;LogFileName=$(Build.SourcesDirectory)/test-results.trx"'

  - script: dotnet tool install -g dotnet-reportgenerator-globaltool
    displayName: 'Install ReportGenerator'

  - script: |
      echo "Debugging files in $(Agent.TempDirectory):"
      find $(Agent.TempDirectory) -name '*' -type f
    displayName: 'Debug Coverage Files'

  - script: |
      reportgenerator \
        -reports:$(Agent.TempDirectory)/**/*.coverage \
        -targetdir:$(Agent.TempDirectory) \
        -reporttypes:Cobertura
    displayName: 'Generate Cobertura Coverage Report'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage to Azure DevOps'
    inputs:
      summaryFileLocation: $(COVERAGE_FILE)

  - task: SonarCloudAnalyze@3
  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'