version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: WebAppUI/Dockerfile 
    ports:
      - "7055:8091"  # Expose port 8091 of the container to port 7055 on the host machine
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api  # Ensure API is running before UI starts

  api:
    build:
      context: .
      dockerfile: WebApplicationApi/Dockerfile
    ports:
      - "7203:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
      - ConnectionStrings__BookshopDatabase=Server=db;Database=BookshopDb;User=sa;Password=My_password123;
    depends_on:
      - db 

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=My_password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: