trigger: none

schedules:
  - cron: "0 8 * * *"
    displayName: "Daily Schedule"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
  - task: DotNetCoreCLI@2
    displayName: 'Build the Project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DockerCompose@1
    displayName: Build Docker Images
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'dockerHub'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'

  - task: DockerCompose@1
    displayName: Push Docker Images
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'dockerHub'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'push'

  - task: DockerCompose@1
    displayName: Start the app
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryEndpoint: 'dockerHub'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'up'
      detached: true

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~End2End'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Test Results as Artifact'
    inputs:
      artifactName: 'TestResults'
      publishLocation: 'Container'
      targetPath: '$(Build.ArtifactStagingDirectory)/TestResults'