trigger: none

schedules:
  - cron: "0 8 * * *"
    displayName: "Daily Schedule"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ACR_NAME: 'bookshop123'
  ACR_URL: '$(ACR_NAME).azurecr.io'
  PROJECT_NAME: 'web_app'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self

  - task: AzureCLI@2
    displayName: Authenticate to Azure Container Registry
    inputs:
      azureSubscription: 'Tatsiana_VS_personal_subscription(69e0488f-40aa-42cb-9421-d421d30469da)' 
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az acr login --name $(ACR_NAME)
  - task: DockerCompose@1
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Tatsiana_VS_personal_subscription(69e0488f-40aa-42cb-9421-d421d30469da)'
      dockerComposeFile: '**/docker-compose.yml'
      azureContainerRegistry: $(ACR_NAME)
      projectName: $(PROJECT_NAME)
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'build'

  - task: DockerCompose@1
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Tatsiana_VS_personal_subscription(69e0488f-40aa-42cb-9421-d421d30469da)'
      dockerComposeFile: '**/docker-compose.yml'
      azureContainerRegistry: $(ACR_NAME)
      projectName: $(PROJECT_NAME)
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'push'

  - task: DockerCompose@1
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Tatsiana_VS_personal_subscription(69e0488f-40aa-42cb-9421-d421d30469da)'
      dockerComposeFile: '**/docker-compose.yml'
      azureContainerRegistry: $(ACR_NAME)
      projectName: $(PROJECT_NAME)
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'up'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~End2End'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Test Results as Artifact'
    inputs:
      artifactName: 'TestResults'
      publishLocation: 'Container'
      targetPath: '$(Build.ArtifactStagingDirectory)/TestResults'