trigger: none
pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_HOST_URL: 'https://sonarcloud.io'
  SONAR_PROJECT_KEY: 'tatsianabaldouskaya_Web_api_app'
  SONAR_ORG_KEY: 'tatsianabaldouskaya-1'
  COVERAGE_FOLDER: '$(Build.SourcesDirectory)/Coverage'
  COVERAGE_FILE: '$(COVERAGE_FOLDER)/coverage.cobertura.xml'

steps:
  - task: UseDotNet@2
    displayName: 'Install SDK'
    inputs:
      version: '8.x'

  - checkout: self
    fetchDepth: 0 

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'sonarToken1'
      organization: 'tatsianabaldouskaya-1'
      scannerMode: 'dotnet'
      projectKey: 'tatsianabaldouskaya_Web_api_app'
      extraProperties: |
        sonar.cs.xunit.reportsPaths=$(COVERAGE_FOLDER)/test-results.trx
        sonar.coverage.cobertura.reportPaths=$(COVERAGE_FILE)
        sonar.scanner.scanAll=false
        sonar.branch.name=main

  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Build the Project'
    inputs:
      command: 'build'
      projects: '**/*.sln'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    continueOnError: false
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~Tests.UnitTests --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=$(System.DefaultWorkingDirectory)/TestResults/unittest-results.trx"'

  - script: |
      echo "Finding and moving coverage file to Coverage directory..."
      mkdir -p $(Build.SourcesDirectory)/Coverage
      find $(Agent.TempDirectory) -name 'coverage.cobertura.xml' -exec cp {} $(Build.SourcesDirectory)/Coverage/ \;
    displayName: 'Locate and Move Coverage File'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage to Azure DevOps'
    inputs:
      summaryFileLocation: '$(Build.SourcesDirectory)/Coverage/coverage.cobertura.xml'

  - task: SonarCloudAnalyze@3
  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'

  - task: DotNetCoreCLI@2
    displayName: 'Run Integration Tests'
    continueOnError: false
    inputs:
      command: 'test'
      projects: '**/Tests.csproj'
      arguments: '--filter FullyQualifiedName~Tests.IntegrationTests --logger:"trx;LogFileName=$(System.DefaultWorkingDirectory)/TestResults/apitest-results.trx"'
  
  - task: PublishTestResults@2
    displayName: 'Publish Test-Results'
    continueOnError: true
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(System.DefaultWorkingDirectory)/TestResults/apitest-results.trx'
      failTaskOnFailedTests: false

  - script: |
      dotnet tool install -g dotnet-reportgenerator-globaltool
      reportgenerator \
        -reports:$(COVERAGE_FILE) \
        -targetdir:$(Build.SourcesDirectory)/Coverage/Report \
        -reporttypes:Html
    displayName: 'Generate HTML Coverage Report'